server {
    listen 8090;
    server_name learn.localhost;

    # Pass shared resources directly to the Quarkus root
    location /Kathisto/ {
        proxy_pass http://127.0.0.1:8081/Kathisto/;
    }

    location /resources/ {
        proxy_pass http://127.0.0.1:8081/resources/;
    }

    # Map everything else to the /learn/ folder in Quarkus
    location / {
        proxy_pass http://127.0.0.1:8081/learn/;
    }
}
