server {
    listen 8090;
    server_name localhost hub-wow.fyi;

    location /Kathisto/ {
        proxy_pass http://127.0.0.1:8081/Kathisto/;
    }

    location /resources/ {
        proxy_pass http://127.0.0.1:8081/resources/;
    }

    location = / {
        proxy_pass http://127.0.0.1:8081/;
    }

    location / {
        proxy_pass http://127.0.0.1:8081/;
    }
}