worker_processes 1;
# error_log /dev/stdout info; # Uncomment to see error logs in terminal
# pid nginx.pid; # Uncomment if you want to store pid locally

events {
    worker_connections 1024;
}

http {
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Common proxy headers for Quarkus `proxy-address-forwarding=true`
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Include specific server configurations
    include servers/*.conf;
}
